apiVersion: v1
kind: ConfigMap
metadata:
  name: chatdocs-config
data:
  PGHOST: "postgres"
  PGDATABASE: "pgllm"
  PGPORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: chatdocs-db-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "psql1234"
