apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatdocs-ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatdocs-ollama
  template:
    metadata:
      labels:
        app: chatdocs-ollama
    spec:
      containers:
        - name: ollama
          image: usersefa/chatdocs-ollama:latest
          ports:
            - containerPort: 11434
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  selector:
    app: chatdocs-ollama
  ports:
    - port: 11434
      targetPort: 11434
      name: http
  type: ClusterIP
